# Site settings
title: Return From Death
tagline: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  Je suis chef de projet et ancien développeur. 
  Je partage ici quelques solutions aux problèmes que j'ai pu rencontrer dans ma carrière.
  J'aime ce qui est simple, clair et épuré.
baseurl: "/returnfromdeath/" # the subpath of your site, e.g. /blog/
url: "http://richard-fagot.github.io" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
homename: "Accueil"
author: "Richard Fagot"
author_thumbnail: "/assets/images/avatar-white.png" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: richard-fagot
    # twitter: 
    # facebook: 
    # gplus: 
    # dribble: gayanvirajith
    # pinterest: 

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

timezone: Europe/Paris

# Permalinks
permalink: /:title/

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
